name: metal-defect-sam
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy=1.24.4
  - scipy=1.15.3
  - scikit-learn=1.7.0
  - scikit-image=0.25.2
  - matplotlib=3.10.3
  - opencv=4.11.0
  - numba=0.61.2
  - lmdb=1.7.2
  - pillow=11.0.0
  - jupyter
  - ipykernel=6.29.5
  - jupyter_client=8.6.3
  - protobuf=6.31.1
  - tornado=6.4.2
  - fonttools=4.58.5
  - typing-extensions=4.12.2
  - pip:
      - torch==2.7.1+cu126
      - torchvision==0.22.1+cu126
      - torchaudio==2.7.1+cu126
      - realesrgan==0.3.0
      - gfpgan==1.3.8
      - facexlib==0.3.0
      - basicsr==1.4.2
      - tb-nightly==2.20.0a20250711
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tqdm==4.32.2
      - requests==2.32.4
      - absl-py==2.3.0
      - PyYAML==6.0.2
      - addict==2.4.0
      - future==1.0.0
      - yapf==0.43.0
      - filterpy==1.4.5
      - imageio==2.37.0
      - six==1.17.0
      - packaging==25.0
      - pyparsing==3.2.3
      - sympy==1.13.3
      - markdown==3.8.2
      - werkzeug==3.1.3
