# config/default.yml

vqvae:
  image_size: 128
  num_hiddens: 128
  num_residual_layers: 2
  num_residual_hiddens: 32
  num_embeddings: 512
  embedding_dim: 64
  commitment_cost: 0.25
  decay: 0.99
  learning_rate: 1e-3
  batch_size: 64
  num_epochs: 50
  checkpoint_dir: checkpoints/vqvae
  save_interval: 5
  log_interval: 10
  device: "cuda"
  num_workers: 4

augment:
  thermal:
    intensity: 0.5  # range from 0 to 1
    probability: 0.9
  grain:
    variance: 0.02
    probability: 0.9
